name: Scrape CI

on:
  schedule:
    - cron: "0 0 15 * *" # Run every month

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Build the project
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      run: npm ci
      run: npm run build --if-present
    - name: Scrape
      run: npm run start
    - name: Push new output to Github
      run: |
          git config --global user.name "evertdespiegeleer"
          git config --global user.email "evert.de.spiegeleer@gmail.com"

          git add -A
          git commit -m "Automatic reindex `date +%d/%m/%Y`"
          git push
